version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-node1
    ports:
      - "5672:5672" # Porta para a comunicação AMQP
      - "15672:15672" # Porta do painel de controle web (Management)
    environment:
      - RABBITMQ_ERLANG_COOKIE=same_cookie_for_both_nodes
    
  mysql:
    image: mysql:latest
    container_name: outbox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admim
      MYSQL_DATABASE: admim
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"